import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../theme/useTheme';

export default function AboutAppScreen({ navigation }: any) {
 const { colors }=useTheme();
 return <SafeAreaView style={[styles.container,{backgroundColor:colors.bg}]}><View style={styles.header}><TouchableOpacity onPress={()=>navigation.goBack()}><Ionicons name="chevron-back" size={26} color={colors.textPrimary}/></TouchableOpacity><Text style={[styles.title,{color:colors.textPrimary}]}>关于应用</Text><View style={{width:26}}/></View><ScrollView contentContainerStyle={styles.content}><View style={[styles.logo,{backgroundColor:colors.avatarBg}]}><Ionicons name="wallet-outline" size={42} color={colors.icon}/></View><Text style={[styles.appName,{color:colors.textPrimary}]}>Personal Finance</Text><Text style={[styles.version,{color:colors.textTertiary}]}>Version 1.0.0</Text><View style={[styles.card,{backgroundColor:colors.card,borderColor:colors.dividerHair}]}><Row label="当前版本" value="1.0.0" colors={colors}/><Row label="版本状态" value="Initial Release" colors={colors}/><Row label="更新内容" value="基础记账 · 预算 · 资产统计" colors={colors}/></View><TouchableOpacity style={[styles.row,{borderColor:colors.dividerHair}]}><Text style={[styles.rowText,{color:colors.textPrimary}]}>检查更新</Text><Ionicons name="chevron-forward" size={18} color={colors.textTertiary}/></TouchableOpacity><Text style={[styles.footer,{color:colors.textTertiary}]}>© 2026 Personal Finance</Text></ScrollView></SafeAreaView>;
}
function Row({label,value,colors}:any){return <View style={styles.infoRow}><Text style={[styles.label,{color:colors.textSecondary}]}>{label}</Text><Text style={[styles.value,{color:colors.textPrimary}]}>{value}</Text></View>}
const styles=StyleSheet.create({container:{flex:1},header:{height:56,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:20},title:{fontSize:17,fontWeight:'700'},content:{alignItems:'center',paddingTop:56,paddingHorizontal:20},logo:{width:86,height:86,borderRadius:24,alignItems:'center',justifyContent:'center'},appName:{fontSize:22,fontWeight:'700',marginTop:16},version:{fontSize:13,marginTop:6},card:{width:'100%',borderWidth:1,borderRadius:18,marginTop:42,paddingHorizontal:16},infoRow:{paddingVertical:17,borderBottomWidth:0},label:{fontSize:12,marginBottom:6},value:{fontSize:15,fontWeight:'500'},row:{width:'100%',height:56,marginTop:14,borderWidth:1,borderRadius:14,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},rowText:{fontSize:15,fontWeight:'500'},footer:{fontSize:11,marginTop:48}});
