export interface CurrencyOption {
  code: string;
  name: string;
  symbol: string;
}

export const CURRENCY_OPTIONS: CurrencyOption[] = [
  { code: 'MYR', name: '马来西亚林吉特', symbol: 'RM' },
  { code: 'CNY', name: '人民币', symbol: '¥' },
  { code: 'USD', name: '美元', symbol: '$' },
  { code: 'EUR', name: '欧元', symbol: '€' },
  { code: 'GBP', name: '英镑', symbol: '£' },
  { code: 'JPY', name: '日元', symbol: '¥' },
  { code: 'SGD', name: '新加坡元', symbol: 'S$' },
  { code: 'HKD', name: '港币', symbol: 'HK$' },
  { code: 'TWD', name: '新台币', symbol: 'NT$' },
  { code: 'AUD', name: '澳元', symbol: 'A$' },
  { code: 'CAD', name: '加元', symbol: 'C$' },
  { code: 'THB', name: '泰铢', symbol: '฿' },
  // —— 扩充：更多国家/地区的主流货币 ——
  { code: 'KRW', name: '韩元', symbol: '₩' },
  { code: 'VND', name: '越南盾', symbol: '₫' },
  { code: 'PHP', name: '菲律宾比索', symbol: '₱' },
  { code: 'IDR', name: '印尼盾', symbol: 'Rp' },
  { code: 'INR', name: '印度卢比', symbol: '₹' },
  { code: 'CHF', name: '瑞士法郎', symbol: 'CHF' },
  { code: 'SEK', name: '瑞典克朗', symbol: 'kr' },
  { code: 'NOK', name: '挪威克朗', symbol: 'kr' },
  { code: 'DKK', name: '丹麦克朗', symbol: 'kr' },
  { code: 'RUB', name: '俄罗斯卢布', symbol: '₽' },
  { code: 'NZD', name: '新西兰元', symbol: 'NZ$' },
  { code: 'BND', name: '文莱元', symbol: 'B$' },
  { code: 'PKR', name: '巴基斯坦卢比', symbol: '₨' },
  { code: 'BDT', name: '孟加拉塔卡', symbol: '৳' },
  { code: 'LKR', name: '斯里兰卡卢比', symbol: 'Rs' },
  { code: 'MMK', name: '缅甸元', symbol: 'K' },
  { code: 'KHR', name: '柬埔寨瑞尔', symbol: '៛' },
  { code: 'LAK', name: '老挝基普', symbol: '₭' },
  { code: 'AED', name: '阿联酋迪拉姆', symbol: 'د.إ' },
  { code: 'SAR', name: '沙特里亚尔', symbol: '﷼' },
  { code: 'QAR', name: '卡塔尔里亚尔', symbol: 'QR' },
  { code: 'TRY', name: '土耳其里拉', symbol: '₺' },
  { code: 'EGP', name: '埃及镑', symbol: 'E£' },
  { code: 'ZAR', name: '南非兰特', symbol: 'R' },
  { code: 'NGN', name: '尼日利亚奈拉', symbol: '₦' },
  { code: 'MXN', name: '墨西哥比索', symbol: 'Mex$' },
  { code: 'BRL', name: '巴西雷亚尔', symbol: 'R$' },
  { code: 'ARS', name: '阿根廷比索', symbol: 'AR$' },
  { code: 'CLP', name: '智利比索', symbol: 'CLP$' },
  { code: 'COP', name: '哥伦比亚比索', symbol: 'COL$' },
  { code: 'PLN', name: '波兰兹罗提', symbol: 'zł' },
  { code: 'CZK', name: '捷克克朗', symbol: 'Kč' },
  { code: 'HUF', name: '匈牙利福林', symbol: 'Ft' },
  { code: 'RON', name: '罗马尼亚列伊', symbol: 'lei' },
  { code: 'UAH', name: '乌克兰格里夫纳', symbol: '₴' },
  { code: 'MOP', name: '澳门元', symbol: 'MOP$' },
];

export function getCurrencySymbol(code: string): string {
  return (
    CURRENCY_OPTIONS.find((c) => c.code === code)?.symbol ??
    WORLD_CURRENCY_OPTIONS.find((c) => c.code === code)?.symbol ??
    code
  );
}

/**
 * 全世界流通货币总表（ISO 4217，~150 种）：添加资产账户页的币种选择用这份。
 * 上面 CURRENCY_OPTIONS（12 种默认 + 常用扩充）保持不变，设置页等地方继续用它。
 * 名称用中文；symbol 未知时给空字符串（界面用 code 兜底显示）。
 */
export const WORLD_CURRENCY_OPTIONS: CurrencyOption[] = [
  ...CURRENCY_OPTIONS,
  { code: 'AFN', name: '阿富汗尼', symbol: '؋' },
  { code: 'ALL', name: '阿尔巴尼亚列克', symbol: 'L' },
  { code: 'AMD', name: '亚美尼亚德拉姆', symbol: '֏' },
  { code: 'ANG', name: '荷属安的列斯盾', symbol: 'ƒ' },
  { code: 'AOA', name: '安哥拉宽扎', symbol: 'Kz' },
  { code: 'AWG', name: '阿鲁巴弗罗林', symbol: 'ƒ' },
  { code: 'AZN', name: '阿塞拜疆马纳特', symbol: '₼' },
  { code: 'BAM', name: '波黑可兑换马克', symbol: 'KM' },
  { code: 'BBD', name: '巴巴多斯元', symbol: 'Bds$' },
  { code: 'BGN', name: '保加利亚列弗', symbol: 'лв' },
  { code: 'BHD', name: '巴林第纳尔', symbol: 'BD' },
  { code: 'BIF', name: '布隆迪法郎', symbol: 'FBu' },
  { code: 'BMD', name: '百慕大元', symbol: '$' },
  { code: 'BOB', name: '玻利维亚诺', symbol: 'Bs' },
  { code: 'BSD', name: '巴哈马元', symbol: 'B$' },
  { code: 'BTN', name: '不丹努尔特鲁姆', symbol: 'Nu.' },
  { code: 'BWP', name: '博茨瓦纳普拉', symbol: 'P' },
  { code: 'BYN', name: '白俄罗斯卢布', symbol: 'Br' },
  { code: 'BZD', name: '伯利兹元', symbol: 'BZ$' },
  { code: 'CDF', name: '刚果法郎', symbol: 'FC' },
  { code: 'CRC', name: '哥斯达黎加科朗', symbol: '₡' },
  { code: 'CUP', name: '古巴比索', symbol: '$' },
  { code: 'CVE', name: '佛得角埃斯库多', symbol: '$' },
  { code: 'DJF', name: '吉布提法郎', symbol: 'Fdj' },
  { code: 'DOP', name: '多米尼加比索', symbol: 'RD$' },
  { code: 'DZD', name: '阿尔及利亚第纳尔', symbol: 'دج' },
  { code: 'ERN', name: '厄立特里亚纳克法', symbol: 'Nfk' },
  { code: 'ETB', name: '埃塞俄比亚比尔', symbol: 'Br' },
  { code: 'FJD', name: '斐济元', symbol: 'FJ$' },
  { code: 'FKP', name: '福克兰群岛镑', symbol: '£' },
  { code: 'GEL', name: '格鲁吉亚拉里', symbol: '₾' },
  { code: 'GHS', name: '加纳塞迪', symbol: '₵' },
  { code: 'GIP', name: '直布罗陀镑', symbol: '£' },
  { code: 'GMD', name: '冈比亚达拉西', symbol: 'D' },
  { code: 'GNF', name: '几内亚法郎', symbol: 'FG' },
  { code: 'GTQ', name: '危地马拉格查尔', symbol: 'Q' },
  { code: 'GYD', name: '圭亚那元', symbol: 'G$' },
  { code: 'HNL', name: '洪都拉斯伦皮拉', symbol: 'L' },
  { code: 'HTG', name: '海地古德', symbol: 'G' },
  { code: 'IQD', name: '伊拉克第纳尔', symbol: 'ع.د' },
  { code: 'IRR', name: '伊朗里亚尔', symbol: '﷼' },
  { code: 'ISK', name: '冰岛克朗', symbol: 'kr' },
  { code: 'JMD', name: '牙买加元', symbol: 'J$' },
  { code: 'JOD', name: '约旦第纳尔', symbol: 'JD' },
  { code: 'KES', name: '肯尼亚先令', symbol: 'KSh' },
  { code: 'KGS', name: '吉尔吉斯斯坦索姆', symbol: 'с' },
  { code: 'KMF', name: '科摩罗法郎', symbol: 'CF' },
  { code: 'KPW', name: '朝鲜圆', symbol: '₩' },
  { code: 'KWD', name: '科威特第纳尔', symbol: 'د.ك' },
  { code: 'KYD', name: '开曼群岛元', symbol: '$' },
  { code: 'KZT', name: '哈萨克斯坦坚戈', symbol: '₸' },
  { code: 'LBP', name: '黎巴嫩镑', symbol: 'ل.ل' },
  { code: 'LRD', name: '利比里亚元', symbol: 'L$' },
  { code: 'LSL', name: '莱索托洛蒂', symbol: 'L' },
  { code: 'LYD', name: '利比亚第纳尔', symbol: 'ل.د' },
  { code: 'MAD', name: '摩洛哥迪拉姆', symbol: 'DH' },
  { code: 'MDL', name: '摩尔多瓦列伊', symbol: 'L' },
  { code: 'MGA', name: '马达加斯加阿里亚里', symbol: 'Ar' },
  { code: 'MKD', name: '马其顿第纳尔', symbol: 'ден' },
  { code: 'MNT', name: '蒙古图格里克', symbol: '₮' },
  { code: 'MRU', name: '毛里塔尼亚乌吉亚', symbol: 'UM' },
  { code: 'MUR', name: '毛里求斯卢比', symbol: '₨' },
  { code: 'MVR', name: '马尔代夫拉菲亚', symbol: 'Rf' },
  { code: 'MWK', name: '马拉维克瓦查', symbol: 'MK' },
  { code: 'NIO', name: '尼加拉瓜科多瓦', symbol: 'C$' },
  { code: 'OMR', name: '阿曼里亚尔', symbol: '﷼' },
  { code: 'PAB', name: '巴拿马巴波亚', symbol: 'B/' },
  { code: 'PEN', name: '秘鲁索尔', symbol: 'S/' },
  { code: 'PGK', name: '巴布亚新几内亚基那', symbol: 'K' },
  { code: 'PYG', name: '巴拉圭瓜拉尼', symbol: '₲' },
  { code: 'RSD', name: '塞尔维亚第纳尔', symbol: 'дин' },
  { code: 'RWF', name: '卢旺达法郎', symbol: 'FRw' },
  { code: 'SBD', name: '所罗门群岛元', symbol: 'SI$' },
  { code: 'SCR', name: '塞舌尔卢比', symbol: '₨' },
  { code: 'SDG', name: '苏丹镑', symbol: 'SDG' },
  { code: 'SHP', name: '圣赫勒拿镑', symbol: '£' },
  { code: 'SLE', name: '塞拉利昂新利昂', symbol: 'Le' },
  { code: 'SOS', name: '索马里先令', symbol: 'Sh' },
  { code: 'SRD', name: '苏里南元', symbol: 'SRD' },
  { code: 'SSP', name: '南苏丹镑', symbol: 'SSP' },
  { code: 'STN', name: '圣多美和普林西比多布拉', symbol: 'Db' },
  { code: 'SVC', name: '萨尔瓦多科朗', symbol: '₡' },
  { code: 'SYP', name: '叙利亚镑', symbol: '£S' },
  { code: 'SZL', name: '斯威士兰里兰吉尼', symbol: 'E' },
  { code: 'TJS', name: '塔吉克斯坦索莫尼', symbol: 'SM' },
  { code: 'TMT', name: '土库曼斯坦马纳特', symbol: 'm' },
  { code: 'TND', name: '突尼斯第纳尔', symbol: 'DT' },
  { code: 'TOP', name: '汤加潘加', symbol: 'T$' },
  { code: 'TTD', name: '特立尼达和多巴哥元', symbol: 'TT$' },
  { code: 'TZS', name: '坦桑尼亚先令', symbol: 'TSh' },
  { code: 'UGX', name: '乌干达先令', symbol: 'USh' },
  { code: 'UYU', name: '乌拉圭比索', symbol: '$U' },
  { code: 'UZS', name: '乌兹别克斯坦索姆', symbol: "so'm" },
  { code: 'VES', name: '委内瑞拉玻利瓦尔', symbol: 'Bs' },
  { code: 'VUV', name: '瓦努阿图瓦图', symbol: 'VT' },
  { code: 'WST', name: '萨摩亚塔拉', symbol: 'WS$' },
  { code: 'YER', name: '也门里亚尔', symbol: '﷼' },
  { code: 'ZMW', name: '赞比亚克瓦查', symbol: 'ZK' },
  { code: 'ZWL', name: '津巴布韦元', symbol: 'Z$' },
];

/** 币种 → 国旗 emoji 的推导兜底：ISO 4217 货币码前两位基本就是国家码（MYR→MY），
 *  用 Unicode 区域指示符拼出国旗；超国家货币（X 开头：XOF/XAF/XPF/XCD）没有对应国旗，返回 undefined。 */
export function getCurrencyFlag(code: string): string | undefined {
  if (CURRENCY_FLAG[code]) return CURRENCY_FLAG[code];
  if (code.startsWith('X')) return undefined;
  const cc = code.slice(0, 2);
  if (!/^[A-Z]{2}$/.test(cc)) return undefined;
  return String.fromCodePoint(...[...cc].map((ch) => 0x1f1e6 + ch.charCodeAt(0) - 65));
}

// 币种 → 国旗 emoji：三星等机型自带 emoji 字体能正常渲染国旗；
// 没匹配到国旗的币种回退成货币符号徽章（安卓部分机型不渲染国旗 emoji，只显示两个字母）。
// 添加资产页和资产页共用这一份映射。
export const CURRENCY_FLAG: Record<string, string> = {
  MYR: '🇲🇾',
  CNY: '🇨🇳',
  USD: '🇺🇸',
  EUR: '🇪🇺',
  GBP: '🇬🇧',
  JPY: '🇯🇵',
  SGD: '🇸🇬',
  HKD: '🇭🇰',
  TWD: '🇹🇼',
  AUD: '🇦🇺',
  CAD: '🇨🇦',
  THB: '🇹🇭',
  KRW: '🇰🇷',
  VND: '🇻🇳',
  PHP: '🇵🇭',
  IDR: '🇮🇩',
  INR: '🇮🇳',
  CHF: '🇨🇭',
  SEK: '🇸🇪',
  NOK: '🇳🇴',
  DKK: '🇩🇰',
  RUB: '🇷🇺',
  NZD: '🇳🇿',
  BND: '🇧🇳',
  PKR: '🇵🇰',
  BDT: '🇧🇩',
  LKR: '🇱🇰',
  MMK: '🇲🇲',
  KHR: '🇰🇭',
  LAK: '🇱🇦',
  AED: '🇦🇪',
  SAR: '🇸🇦',
  QAR: '🇶🇦',
  TRY: '🇹🇷',
  EGP: '🇪🇬',
  ZAR: '🇿🇦',
  NGN: '🇳🇬',
  MXN: '🇲🇽',
  BRL: '🇧🇷',
  ARS: '🇦🇷',
  CLP: '🇨🇱',
  COP: '🇨🇴',
  PLN: '🇵🇱',
  CZK: '🇨🇿',
  HUF: '🇭🇺',
  RON: '🇷🇴',
  UAH: '🇺🇦',
  MOP: '🇲🇴',
  // —— 特殊/超国家币种覆盖 ——
  ANG: '🇨🇼', // 荷属安的列斯已解体，AN 区旗在多数字体不渲染，用库拉索旗（ANG 现流通地）
};
