import { Category } from '../types';

export const DEFAULT_CATEGORIES: Category[] = [
  // 支出分类
  { id: 'food', name: '餐饮', icon: 'restaurant-outline', color: '#FF7A5C', type: 'expense' },
  { id: 'shopping', name: '购物', icon: 'bag-handle-outline', color: '#B983FF', type: 'expense' },
  { id: 'daily', name: '日用', icon: 'basket-outline', color: '#8D9AAF', type: 'expense' },
  { id: 'transport', name: '交通', icon: 'bus-outline', color: '#4C9AFF', type: 'expense' },
  { id: 'vegetable', name: '蔬菜', icon: 'leaf-outline', color: '#66BB6A', type: 'expense' },
  { id: 'fruit', name: '水果', icon: 'nutrition-outline', color: '#EF5350', type: 'expense' },
  { id: 'snack', name: '零食', icon: 'ice-cream-outline', color: '#EC407A', type: 'expense' },
  { id: 'sport', name: '运动', icon: 'fitness-outline', color: '#26A69A', type: 'expense' },
  { id: 'entertainment', name: '娱乐', icon: 'game-controller-outline', color: '#AB47BC', type: 'expense' },
  { id: 'communication', name: '通讯', icon: 'call-outline', color: '#42A5F5', type: 'expense' },
  { id: 'clothes', name: '服饰', icon: 'shirt-outline', color: '#FFA726', type: 'expense' },
  { id: 'beauty', name: '美容', icon: 'sparkles-outline', color: '#F06292', type: 'expense' },
  { id: 'rent', name: '住房', icon: 'home-outline', color: '#FF9F43', type: 'expense' },
  { id: 'home', name: '居家', icon: 'cube-outline', color: '#8D6E63', type: 'expense' },
  { id: 'kids', name: '孩子', icon: 'happy-outline', color: '#FFCA28', type: 'expense' },
  { id: 'elders', name: '长辈', icon: 'people-outline', color: '#A1887F', type: 'expense' },
  { id: 'social', name: '社交', icon: 'chatbubbles-outline', color: '#5C6BC0', type: 'expense' },
  { id: 'travel', name: '旅行', icon: 'airplane-outline', color: '#29B6F6', type: 'expense' },
  { id: 'tobacco_alcohol', name: '烟酒', icon: 'wine-outline', color: '#8E24AA', type: 'expense' },
  { id: 'digital', name: '数码', icon: 'hardware-chip-outline', color: '#546E7A', type: 'expense' },
  { id: 'car', name: '汽车', icon: 'car-outline', color: '#3949AB', type: 'expense' },
  { id: 'medical', name: '医疗', icon: 'medkit-outline', color: '#66BB6A', type: 'expense' },
  { id: 'books', name: '书籍', icon: 'book-outline', color: '#7E57C2', type: 'expense' },
  { id: 'study', name: '学习', icon: 'school-outline', color: '#26C6DA', type: 'expense' },
  { id: 'pet', name: '宠物', icon: 'paw-outline', color: '#8D6E63', type: 'expense' },
  { id: 'cash_gift', name: '礼金', icon: 'wallet-outline', color: '#E53935', type: 'expense' },
  { id: 'gift', name: '礼物', icon: 'gift-outline', color: '#F9A825', type: 'expense' },
  { id: 'office', name: '办公', icon: 'briefcase-outline', color: '#607D8B', type: 'expense' },
  { id: 'repair', name: '维修', icon: 'construct-outline', color: '#78909C', type: 'expense' },
  { id: 'other_expense', name: '其他', icon: 'ellipsis-horizontal-circle-outline', color: '#9E9E9E', type: 'expense' },
  { id: 'transfer_fee', name: '手续费', icon: 'swap-horizontal-outline', color: '#EF5350', type: 'expense' },

  // 收入分类
  { id: 'salary', name: '工资', icon: 'cash-outline', color: '#43A047', type: 'income' },
  { id: 'bonus', name: '奖金', icon: 'trophy-outline', color: '#F9A825', type: 'income' },
  { id: 'parttime', name: '兼职', icon: 'time-outline', color: '#00897B', type: 'income' },
  { id: 'investment', name: '理财', icon: 'trending-up-outline', color: '#1E88E5', type: 'income' },
  { id: 'red_packet', name: '红包', icon: 'pricetag-outline', color: '#E53935', type: 'income' },
  { id: 'other_income', name: '其他收入', icon: 'add-circle-outline', color: '#7CB342', type: 'income' },
];
